# PostgreSQL Configuration
spring.datasource.url = jdbc:postgresql://dpg-da27jdn40ujc739aba10-a.singapore-postgres.render.com/moneymanager_rckq
spring.datasource.username=moneymanager_rckq_user
spring.datasource.password=TNEyuX755xL5D0ugMl0mXwPQLYJgyeSI